env:
  global:
    - CC_TEST_REPORTER_ID=3973d29c9191b3e9f1cca55d092c31d7c249b6bff79bba977f1944e6a7fa38cf

language: python

#services:
#  - docker

python:
  - "2.7"
  - "3.4"

# command to install dependencies
before_install:
#- docker build --force-rm=true --build-arg TRAVIS_BRANCH=${TRAVIS_BRANCH} --build-arg TRAVIS_EVENT_TYPE=${TRAVIS_EVENT_TYPE} --build-arg TRAVIS_PULL_REQUEST_SLUG=${TRAVIS_PULL_REQUEST_SLUG} --build-arg TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH} -t intelora-ubuntu1604 -f tests/docker/ubuntu_16_04.dockerfile .
#- docker build --force-rm=true --build-arg TRAVIS_BRANCH=${TRAVIS_BRANCH} --build-arg TRAVIS_EVENT_TYPE=${TRAVIS_EVENT_TYPE} --build-arg TRAVIS_PULL_REQUEST_SLUG=${TRAVIS_PULL_REQUEST_SLUG} --build-arg TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH} -t intelora-debian8 -f tests/docker/debian8.dockerfile .
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse"
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty-updates main restricted universe multiverse"
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
- sudo apt-get update
- sudo apt-get install $(cat tests/requirements/deb-requirements.txt)
- sudo apt-get install libstdc++6 libpython3.4-dev
- wget https://bootstrap.pypa.io/get-pip.py
- sudo python get-pip.py

install:
  - pip install -r tests/requirements/python-requirements.txt
  - pip install python2-pythondialog || pip install pythondialog
  - pip install coveralls

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# command to run tests
script:
   - python setup.py install
   - cd tests/linux/
   - intelora start --run-order "hello"
#  - docker run -it --rm intelora-ubuntu1604
#  - docker run -it --rm intelora-debian8
#  - coverage run --source=intelora -m unittest discover

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  coveralls

notifications:
    slack: intelora:xmCtDNSS8C1T1EKvBjATSXNA